import { type GameState, StackTypes } from '$lib/game/types';

export const gameState = $state<GameState>({
	stacks: [
		{ id: '-1', cards: [], type: StackTypes.NULL },
		{ id: 'B0', cards: [], type: StackTypes.BORDER },
		{ id: 'B1', cards: [], type: StackTypes.BORDER },
		{ id: 'B2', cards: [], type: StackTypes.BORDER },
		{ id: '-1', cards: [], type: StackTypes.NULL },
		{ id: 'B3', cards: [], type: StackTypes.BORDER },
		{ id: 'C0', cards: [], type: StackTypes.CENTER },
		{ id: 'C1', cards: [], type: StackTypes.CENTER },
		{ id: 'C2', cards: [], type: StackTypes.CENTER },
		{ id: 'B4', cards: [], type: StackTypes.BORDER },
		{ id: 'B5', cards: [], type: StackTypes.BORDER },
		{ id: 'C3', cards: [], type: StackTypes.CENTER },
		{ id: 'C4', cards: [], type: StackTypes.CENTER },
		{ id: 'C5', cards: [], type: StackTypes.CENTER },
		{ id: 'B6', cards: [], type: StackTypes.BORDER },
		{ id: 'B7', cards: [], type: StackTypes.BORDER },
		{ id: 'C6', cards: [], type: StackTypes.CENTER },
		{ id: 'C7', cards: [], type: StackTypes.CENTER },
		{ id: 'C8', cards: [], type: StackTypes.CENTER },
		{ id: 'B8', cards: [], type: StackTypes.BORDER },
		{ id: '-1', cards: [], type: StackTypes.NULL },
		{ id: 'B9', cards: [], type: StackTypes.BORDER },
		{ id: 'B10', cards: [], type: StackTypes.BORDER },
		{ id: 'B11', cards: [], type: StackTypes.BORDER },
		{ id: '-1', cards: [], type: StackTypes.NULL },
	],
	draw: { id: 'draw', cards: [], type: StackTypes.DRAW },
	jokers: { id: 'jokers', cards: [], type: StackTypes.JOKERS },
	aces: { id: 'aces', cards: [], type: StackTypes.ACES },
	royals: { id: 'royals', cards: [], type: StackTypes.ROYALS },
	draggingCard: null
});